abstract: inflate object from request or session.
author: Tokuhiro Matsuno  C<< <tokuhiro __at__ mobilefactory.jp> >>
build_requires: 
  Test::Base: 0.50
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Sledge-Plugin-Inflate
no_index: 
  directory: 
    - inc
    - t
version: 0.02
